server {
    listen 80;
    server_name localhost;

    # Redireccionar / a /ds
    location = / {
        return 301 /ds;
    }

    location /ds {
        alias /usr/share/nginx/html/;
        index index.html;
        try_files $uri $uri/ /ds/index.html;
    }

    # Redirigir errores al index.html
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}