spring:
  application:
    name: auth-service
  mongodb:
    uri: ${SPRING_MONGODB_URI:mongodb://mongodb:27017/dresstyle_auth}

  rabbitmq:
    host: rabbitmq # Nombre del servicio definido en docker-compose
    port: 5672
    username: ${SPRING_RABBITMQ_USERNAME:admin}
    password: ${SPRING_RABBITMQ_PASSWORD:admin123}


eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

server:
  port: 8081 # Puerto específico para este servicio

jwt:
  # Esta clave debe ser una cadena larga en Base64
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: 86400000 # 24 horas

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

