server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    # Como este es el servidor, le decimos que no intente registrarse a sí mismo
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: discovery-server
